namespace AINotebook.App.Services;

/// <summary>PascalCase mirror of the mac AppText.Key cases (148). Convenience for
/// compile-time-checked lookups; resolves to the same .resw entry as the string key.</summary>
public enum StringKey
{
    AppName, Settings, Language, Version, Notebooks, Sources, Chat, Notes, Transformations,
    NoNotebookSelected, CreateNotebook, RenameNotebook, DeleteNotebook, NotebookName,
    NotebookDescription, Cancel, Create, Save, Delete, ConfirmDeleteNotebook, CannotBeEmpty,
    Welcome, WelcomeBody, ContinueLabel, OnboardingDetectTitle, OnboardingDetectBody,
    OnboardingDetectChecking, OnboardingDetectFound, OpenOllamaDownload,
    OnboardingDetectWaiting, OnboardingPickModelsTitle, OnboardingPickModelsBody, ChatModel,
    EmbeddingModel, OnboardingPullTitle, OnboardingPullBody, OnboardingPullingChat,
    OnboardingPullingEmbedding, OnboardingDoneTitle, OnboardingDoneBody, OllamaUnreachable,
    StartUsingApp, SourcesSectionTitle, AddSourceButton, AddSourceSheetTitle,
    AddSourceFromFile, AddSourceFromURL, AddSourceFromText, AddSourceURLPlaceholder,
    AddSourceTitlePlaceholder, AddSourceTextPlaceholder, AddSourceConfirm, CancelButton,
    SourceStatusPending, SourceStatusChunking, SourceStatusReady, SourceStatusError,
    NoSourcesEmptyState, DeleteSourceConfirm, DeleteButton, IndexingInProgress,
    IndexingProgressFormat, IndexingComplete, IndexingError, IndexingPaused, IndexingIdle,
    ChatNewSessionTitle, ChatInputPlaceholder, ChatSendButton, ChatEmptyState, ChatErrorPrefix,
    ChatCitationsSectionTitle, ChatNoCitationsForMessage, ChatRegenerateButton,
    ChatSessionsLabel, ChatNewSessionButton, ChatDeleteSessionButton, ChatSaveAsNoteButton,
    NotesSectionTitle, NotesEmptyState, NotesNewButton, NoteUntitled, NoteTitlePlaceholder,
    NoteBodyPlaceholder, NoteOriginManual, NoteOriginChat, NoteOriginTransformation,
    TransformationsSectionTitle, TransformationPickerLabel, TransformationSourcePickerLabel,
    TransformationRunButton, TransformationResultTitle, TransformationRunningStatus,
    TransformationEditButton, TransformationEditorTitle, TransformationEditorNew,
    TransformationEditorDelete, TransformationEditorNamePlaceholder,
    TransformationEditorTemplatePlaceholder, ReembedButton, ReembedConfirm, ReembedConfirmYes,
    EmbeddingSectionTitle, CurrentModelLabel, ManageModelsButton, ManageModelsTitle,
    ManageModelsPullPlaceholder, ManageModelsPullButton, ManageModelsRefreshButton,
    ManageModelsDeleteTitle, ManageModelsDeleteConfirm,
    ChatModelPickerLabel, EmbeddingModelPickerLabel, OpenNoteFromCitation, NotesChatPanelTitle,
    NotesChatPanelEmpty, NotesChatCurrentNoteHint, EditorStatusSaved, EditorStatusSaving,
    EditorStatusUnsaved, EditorStatusError, EditorFailedToLoad, AttachmentBrokenLink,
    AttachmentSaveFailed, AttachmentOpenButton, HistoryButton, HistorySheetTitle, HistoryEmpty,
    HistoryRestoreButton, HistoryReasonAutosave, HistoryReasonRestore, AiToolsSectionTitle,
    AiToolsEmptyTitle, AiToolsEmptyBody, AiToolsScopeAllSources, AiToolsScopeHint,
    AiToolsPreviewButton, AiToolsHistoryButton, AiToolsResultSavedFormat,
    AiToolsOpenNoteButton, AiToolsRunningFormat, AiToolsBatchSavedFormat,
    AiToolsPromptPreviewTitle, AiToolsHistoryEmpty, AiToolsHistoryTitle,
    AiToolsDescriptionPlaceholder, UnsavedChangesTitle, UnsavedChangesMessage,
    UnsavedSaveButton, UnsavedDiscardButton,
    // NotebookLM Stage C: follow-up chips, per-source summary, chat source scope.
    ChatFollowupsLabel, SourceSummaryLabel, SourceSummarizeButton, SourceSummarizingStatus,
    ChatScopeButton, ChatScopeAllSources, ChatScopeTitle,
    // Epic A: multi-provider AI support.
    ProvidersSectionTitle, AddProviderButton, AddProviderTitle, EditProviderTitle,
    ProviderTypeLabel, ProviderNameLabel, ProviderUrlLabel,
    ProviderApiKeyLabel, ProviderApiKeyPlaceholder,
    ProviderTestButton, ProviderTestSuccess,
    ProviderDeleteTitle, ProviderDeleteConfirm,
    PrivacyGateTitle, PrivacyGateBody, PrivacyGateAcknowledge,
    ChatProviderPickerLabel, EmbeddingProviderPickerLabel,
    ErrorConsentRequired,
    // Epic B: export, search, drag&drop, tags, bulk ops.
    NoteSearchPlaceholder,
    SourcePreviewTitle, SourcePreviewChunksLabel, SourcePreviewNoContent, SourcePreviewButton,
    ExportNoteButton, ExportNoteMarkdown, ExportNotebookButton, ExportNotebookZip,
    BackupButton, BackupRestoreButton, BackupRestoreConfirm, ExportSuccess,
    GlobalSearchTitle, GlobalSearchPlaceholder, GlobalSearchEmpty,
    GlobalSearchSectionNotes, GlobalSearchSectionSources,
    BulkSelectButton, BulkDeleteSelectedButton, BulkDeleteConfirmFormat, BulkSummarizeSelectedButton,
    TagsSectionTitle, AddTagButton, TagNamePlaceholder, FilterByTagLabel, AllTagsOption, DeleteTagTitle,
    // Epic C: chat quality.
    NotebookInstructionsLabel, NotebookInstructionsPlaceholder, NotebookInstructionsSaved,
    SourceSetsSectionTitle, AddSourceSetButton, SourceSetNamePlaceholder, DeleteSourceSetTitle,
    ChatEditButton, ChatRegenerateWithButton,
    CitationPanelTitle, CitationPanelEmpty,
    // Epic D: retrieval quality.
    ContextualEnrichmentLabel, ContextualEnrichmentHint,
    // Epic E: live sources.
    FolderWatchButton, FolderWatchActiveLabel,
    UrlRefreshButton, UrlRefreshingStatus,
    WebSearchToggleLabel, WebSearchResultsTitle, WebSearchEmpty,
}
